let data = [
  [
    "Brent Fuentes",
    "Lorem Lorem Luctus Institute",
    "turpis@felisDonec.org",
    "13/08/2020",
    "Bhutan",
    "İskenderun",
  ],
  [
    "Alana Hobbs",
    "Lacinia Ltd",
    "tincidunt@Duismi.org",
    "17/02/2022",
    "Dominica",
    "Tontelange",
  ],
  [
    "Bruno Pearson",
    "Arcu Vestibulum Incorporated",
    "pede.blandit.congue@convallisin.ca",
    "30/04/2022",
    "Australia",
    "Kaaskerke",
  ],
  [
    "Colorado Farrell",
    "Sed Dui Consulting",
    "ultricies@Vivamusnonlorem.edu",
    "18/12/2020",
    "Maldives",
    "Peñaflor",
  ],
  [
    "Nicholas Vincent",
    "Facilisis LLC",
    "nec.tempus@metusIn.co.uk",
    "12/06/2022",
    "Bulgaria",
    "Piura",
  ],
  [
    "Blythe Bauer",
    "Id Enim Curabitur LLC",
    "Mauris@Aliquamrutrum.edu",
    "02/03/2021",
    "Comoros",
    "Sherborne",
  ],
  [
    "Sacha Hughes",
    "In Sodales LLC",
    "non.nisi@enim.com",
    "25/04/2022",
    "Argentina",
    "Rzeszów",
  ],
  [
    "Isabelle Prince",
    "A Feugiat Tellus Consulting",
    "amet@purusinmolestie.edu",
    "16/10/2020",
    "Iceland",
    "Perwez",
  ],
  [
    "Serena Grant",
    "Auctor Mauris Vel Corp.",
    "aliquam.eros@eget.org",
    "31/08/2020",
    "Anguilla",
    "Saint-Sébastien-sur-Loire",
  ],
  [
    "Brenda Atkins",
    "Gravida Non Company",
    "massa@parturientmontesnascetur.com",
    "24/09/2020",
    "South Africa",
    "Kopeysk",
  ],
  [
    "Aspen Beard",
    "Dui Corp.",
    "dictum.eleifend.nunc@tincidunt.net",
    "02/11/2021",
    "Kuwait",
    "Biez",
  ],
  [
    "Caesar Odom",
    "Enim Etiam Gravida Consulting",
    "quis@egetvenenatis.edu",
    "20/09/2021",
    "United Kingdom (Great Britain)",
    "Meux",
  ],
  [
    "Vance Burris",
    "Elit Pellentesque A Associates",
    "sem.magna.nec@enimsit.co.uk",
    "20/05/2022",
    "Armenia",
    "San Marcello",
  ],
  [
    "Anthony Barry",
    "Et PC",
    "Vivamus.non.lorem@mollisnon.ca",
    "31/12/2020",
    "Finland",
    "Rajahmundry",
  ],
  [
    "Cyrus Heath",
    "Libero At Consulting",
    "purus.sapien@telluseuaugue.com",
    "04/05/2021",
    "Dominican Republic",
    "Williams Lake",
  ],
  [
    "Galena Lambert",
    "Amet Metus Aliquam Industries",
    "a@miDuisrisus.ca",
    "28/09/2020",
    "Qatar",
    "Masone",
  ],
  [
    "Jaquelyn Goff",
    "Ornare Facilisis Eget PC",
    "dolor.elit.pellentesque@cursuspurusNullam.net",
    "11/01/2022",
    "Saint Vincent and The Grenadines",
    "Accadia",
  ],
  [
    "Dane Gomez",
    "Nulla Ltd",
    "pede.Suspendisse@at.edu",
    "29/12/2020",
    "Peru",
    "Monteleone di Spoleto",
  ],
  [
    "Quyn Phillips",
    "Luctus PC",
    "aliquet@Craseget.com",
    "22/07/2021",
    "Tunisia",
    "Rostov",
  ],
  [
    "Inga Barry",
    "Velit Foundation",
    "In.mi@eulacus.edu",
    "15/11/2020",
    "Bosnia and Herzegovina",
    "Pietraroja",
  ],
  [
    "Amir Morse",
    "Interdum Associates",
    "vulputate@Aeneangravida.co.uk",
    "07/11/2021",
    "Puerto Rico",
    "Toernich",
  ],
  [
    "Jorden Woods",
    "Suspendisse Commodo Tincidunt PC",
    "sem.consequat@mi.net",
    "04/12/2021",
    "Tajikistan",
    "Combarbalá",
  ],
  [
    "Aaron Webb",
    "Augue Ut LLC",
    "Nam.tempor@arcu.ca",
    "08/05/2021",
    "Denmark",
    "Pathankot",
  ],
  [
    "Sara Johns",
    "Pretium Et Incorporated",
    "Vivamus.nisi@auctor.ca",
    "04/01/2021",
    "Suriname",
    "Gignod",
  ],
  [
    "Brett Mcbride",
    "Faucibus Morbi Vehicula Corporation",
    "faucibus.orci@Nullamscelerisqueneque.org",
    "06/05/2021",
    "Pitcairn Islands",
    "Burcht",
  ],
  [
    "Zephr Burns",
    "Erat Volutpat Nulla Inc.",
    "id.blandit@cubilia.net",
    "04/09/2020",
    "Åland Islands",
    "Attert",
  ],
  [
    "Rhona Mooney",
    "Sed Et PC",
    "placerat@sodalesat.ca",
    "10/11/2020",
    "Azerbaijan",
    "Shrewsbury",
  ],
];

let labels = ["Name Surname", "Company", "Email", "Date", "Country", "City"];

let arr = [];
let obj = {};

for (let i = 0; i < data.length; i++) {
  for (let j = 0; j < labels.length; j++) {
    obj[labels[j]] = data[i][j];
  }

  arr.push(JSON.parse(JSON.stringify(obj)));
  //   console.log(obj);
}
console.log(arr);
